<?php

namespace App\Http\Requests\Interviews;

use Illuminate\Foundation\Http\FormRequest;

class CreateInterviewRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true; // checked in controller
    }

    public function rules(): array
    {
        return [
            'candidate_id' => ['required', 'uuid'],
            'job_id' => ['required', 'uuid'],
            'organizer_id' => ['required', 'uuid'],
            'interview_type' => ['nullable', 'string', 'max:255'],
            // Schema's provider ENUM — video-conferencing only, per the
            // actual migration (no 'phone'/'onsite' option exists).
            'provider' => ['required', 'in:google_meet,microsoft_teams,zoom'],
            // For provider='google_meet' with the organizer's Google
            // account connected (see OAuthConnectController), this is
            // now AUTO-GENERATED by InterviewService via Google
            // Calendar API and overwrites whatever is submitted here —
            // so meeting_url stays optional/nullable: it's a manual
            // fallback for when Google isn't connected, or for
            // microsoft_teams/zoom (still manual, no OAuth wired yet
            // for those two providers).
            'meeting_url' => ['nullable', 'url', 'max:500'],
            'start_time' => ['required', 'date'],
            'end_time' => ['required', 'date', 'after:start_time'],
        ];
    }
}
